"""Bundle Python source into a standalone Bash entry point, with no temp files."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def build():
    source = (ROOT / "ip_quality.py").read_text(encoding="utf-8")
    return '''#!/usr/bin/env bash
# Generated by scripts/build_launcher.py. Edit ip_quality.py, then rebuild.
# Standalone: works through process substitution, with no checkout or root needed.
set -euo pipefail
python_command=""
for candidate in python3 python; do
    if command -v "$candidate" >/dev/null 2>&1 &&
        "$candidate" -c 'import sys; sys.exit(sys.version_info < (3, 9))' 2>/dev/null; then
        python_command="$candidate"
        break
    fi
done
if [[ -z "$python_command" ]]; then
    printf '%s\\n' '需要 Python 3.9+ / Python 3.9+ is required (no pip packages needed).' >&2
    exit 1
fi
# -c leaves stdin free for the IP prompt, including when run as bash <(curl ...).
exec "$python_command" -c "$(cat <<'NODEQUALITY_PYTHON'
''' + source + '''NODEQUALITY_PYTHON
)" "$@"
'''


if __name__ == "__main__":
    with (ROOT / "NodeQuality.sh").open("w", encoding="utf-8", newline="\n") as output:
        output.write(build())
